spring:
  application:
    name: local-scheduler-agent
server:
  port: 8081

# 多集群LSA配置
lsa:
  clusters:
    configs:
      - name: kwok-cluster01
        kubeconfigPath: E:\kubeconfig\my-kubeconfig-01.yaml
      - name: kwok-cluster02
        kubeconfigPath: E:\kubeconfig\my-kubeconfig-02.yaml
      - name: kwok-cluster03
        kubeconfigPath: E:\kubeconfig\my-kubeconfig-03.yaml
      - name: kwok-cluster04
        kubeconfigPath: E:\kubeconfig\my-kubeconfig-04.yaml
      - name: kwok-cluster05
        kubeconfigPath: E:\kubeconfig\my-kubeconfig-05.yaml
      # 如果是 kwok 模拟环境，也可以使用共享配置
      # - name: karmada-kwok-01
      #   kubeconfigPath: /etc/karmada/kwok/kubeconfig.yaml

global:
  scheduler:
    url: http://localhost:8080