spring:
  application:
    name: local-scheduler-agent
server:
  port: 8081

# 多集群LSA配置
lsa:
  clusters:
    configs:
      - name: member1
        kubeconfigPath: E:\kubeconfig\member1.kubeconfig
      - name: member2
        kubeconfigPath: E:\kubeconfig\member2.kubeconfig
      - name: member3
        kubeconfigPath: E:\kubeconfig\member3.kubeconfig
      # 如果是 kwok 模拟环境，也可以使用共享配置
      # - name: karmada-kwok-01
      #   kubeconfigPath: /etc/karmada/kwok/kubeconfig.yaml

global:
  scheduler:
    url: http://localhost:8088