spring.application.name=bridge
server.port=8082

# æå® Karmada æ§å¶é¢ç kubeconfig
kubeconfig.path=E:\karmada-config

# Global Scheduler æå¡å°å
global.scheduler.url=http://localhost:8080
