k8s:
  client:
    verifySsl: false
    readTimeout: 0
    defaultKubeconfigPath: E:\karmada-config
spring:
  application:
    name: bridge
server:
  port: 8082
global:
  scheduler:
    url: http://localhost:80800
